export const TAROT_CARDS = [
  {
    id: 'the-fool',
    name: 'The Fool',
    number: 0,
    arcana: 'major',
    visualDescription: 'A young man stands on the edge of a cliff, looking up at the sky. He carries a small knapsack and a white rose. A small white dog leaps at his heels.',
    designInterpretation: 'Represents the beginning of a journey, innocence, and the leap of faith into the unknown.',
    uprightMeaning: 'New beginnings, innocence, spontaneity, a free spirit.',
    reversedMeaning: 'Recklessness, risk-taking, inconsideration, holding back.',
    keywords: ['Innocence', 'Beginnings', 'Free Spirit', 'Spontaneity'],
    emotionalTone: 'Optimistic, lighthearted, carefree.',
    archetype: 'The Innocent / The Wanderer',
    element: 'Air',
    numerology: '0 (The source of all, the void, infinite potential)',
    suitEnergy: 'N/A'
  },
  {
    id: 'the-magician',
    name: 'The Magician',
    number: 1,
    arcana: 'major',
    visualDescription: 'A figure stands with one arm pointing to the sky and the other to the earth. On a table before him are a wand, cup, sword, and pentacle.',
    designInterpretation: 'Symbolizes the bridge between the spiritual and physical worlds, and the mastery of the four elements.',
    uprightMeaning: 'Manifestation, resourcefulness, power, inspired action.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents.',
    keywords: ['Manifestation', 'Power', 'Action', 'Resourcefulness'],
    emotionalTone: 'Confident, empowered, focused.',
    archetype: 'The Magus / The Creator',
    element: 'Air',
    numerology: '1 (New beginnings, focus, individuality)',
    suitEnergy: 'N/A'
  },
  {
    id: 'the-high-priestess',
    name: 'The High Priestess',
    number: 2,
    arcana: 'major',
    visualDescription: 'A woman sits between two pillars, one black and one white. She wears a crown with a crescent moon and holds a scroll.',
    designInterpretation: 'Represents the veil between the conscious and subconscious, and the wisdom found in silence.',
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, the subconscious mind.',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal and silence.',
    keywords: ['Intuition', 'Mystery', 'Subconscious', 'Silence'],
    emotionalTone: 'Serene, mysterious, deep.',
    archetype: 'The Oracle / The Inner Voice',
    element: 'Water',
    numerology: '2 (Duality, balance, reflection)',
    suitEnergy: 'N/A'
  },
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    number: 1,
    arcana: 'minor',
    suit: 'cups',
    visualDescription: 'A hand emerges from a cloud holding a cup overflowing with five streams of water. A dove descends towards the cup.',
    designInterpretation: 'The overflow of emotion and the beginning of spiritual or emotional fulfillment.',
    uprightMeaning: 'Love, new relationships, compassion, creativity.',
    reversedMeaning: 'Self-love, repressed emotions, blocked creativity.',
    keywords: ['Love', 'Compassion', 'Creativity', 'Emotion'],
    emotionalTone: 'Joyful, peaceful, overflowing.',
    archetype: 'The Vessel',
    element: 'Water',
    numerology: '1 (New beginnings, seeds of potential)',
    suitEnergy: 'Emotional, intuitive, fluid'
  }
];
