import React, { useState } from 'react';
import GameTemplate from '../GameTemplate';
import { Sparkles } from 'lucide-react';
import './lunaCustomGame.css';

const LunaCustomGame = ({ onComplete, onBack }) => {
  const [score, setScore] = useState(0);
  const [isFinished, setIsFinished] = useState(false);
  const [remediationData, setRemediationData] = useState([]);

  const handleAnswer = (isCorrect) => {
    if (isCorrect) {
      setScore(100);
    } else {
      setScore(0);
      setRemediationData([{
        question: "Luna's Mystery Challenge",
        explanation: "The cards are mirrors of the soul. Trust your first intuitive spark above all else."
      }]);
    }
    setIsFinished(true);
  };

  const handleRetry = () => {
    setScore(0);
    setIsFinished(false);
    setRemediationData([]);
  };

  return (
    <GameTemplate
      title="Luna's Secret Challenge"
      description="A unique challenge generated by Luna herself, testing your pure intuition."
      score={score}
      isFinished={isFinished}
      remediationData={remediationData}
      onComplete={onComplete}
      onBack={onBack}
      onRetry={handleRetry}
    >
      <div className="lc-container">
        <div className="lc-luna-avatar">
          <Sparkles size={48} className="lc-sparkle" />
        </div>
        <div className="lc-message-box">
          <p className="lc-luna-text">"Finder, close your eyes for a moment. Feel the energy of the deck. Which card is calling to you from the void right now?"</p>
        </div>
        <div className="lc-options">
          <button className="lc-option-btn" onClick={() => handleAnswer(true)}>The Fool (New Beginnings)</button>
          <button className="lc-option-btn" onClick={() => handleAnswer(false)}>The Tower (Sudden Change)</button>
          <button className="lc-option-btn" onClick={() => handleAnswer(true)}>The Star (Hope)</button>
          <button className="lc-option-btn" onClick={() => handleAnswer(false)}>The Moon (Illusions)</button>
        </div>
      </div>
    </GameTemplate>
  );
};

export default LunaCustomGame;
