import React, { lazy } from 'react';

export const GAMES = {
  'matching': {
    id: 'matching',
    title: 'Arcana Matching',
    description: 'Match the Major Arcana names with their archetypal meanings.',
    component: lazy(() => import('./Matching/MatchingGame'))
  },
  'multiple-choice': {
    id: 'multiple-choice',
    title: 'Tarot Trivia',
    description: 'Test your knowledge of tarot history and symbolism.',
    component: lazy(() => import('./MultipleChoice/MultipleChoiceGame'))
  },
  'card-design-match': {
    id: 'card-design-match',
    title: 'Design Synthesis',
    description: 'Match design elements with the correct tarot deck style.',
    component: lazy(() => import('./CardDesignMatch/CardDesignMatchGame'))
  },
  'symbol-match': {
    id: 'symbol-match',
    title: 'Symbolic Insight',
    description: 'Identify the hidden symbols within the cards.',
    component: lazy(() => import('./SymbolMatch/SymbolMatchGame'))
  },
  'emotion-match': {
    id: 'emotion-match',
    title: 'Emotional Resonance',
    description: 'Connect the cards with the emotions they evoke.',
    component: lazy(() => import('./EmotionMatch/EmotionMatchGame'))
  },
  'story-builder': {
    id: 'story-builder',
    title: 'The Fool\'s Narrative',
    description: 'Construct a coherent story using a sequence of cards.',
    component: lazy(() => import('./StoryBuilder/StoryBuilderGame'))
  },
  'spread-builder': {
    id: 'spread-builder',
    title: 'Spread Architect',
    description: 'Design the perfect spread for a specific inquiry.',
    component: lazy(() => import('./SpreadBuilder/SpreadBuilderGame'))
  },
  'timed-challenge': {
    id: 'timed-challenge',
    title: 'Intuitive Sprint',
    description: 'Quick-fire card identification under pressure.',
    component: lazy(() => import('./TimedChallenge/TimedChallengeGame'))
  },
  'design-memory': {
    id: 'design-memory',
    title: 'Visual Recall',
    description: 'Recall the intricate details of card illustrations.',
    component: lazy(() => import('./DesignMemory/DesignMemoryGame'))
  },
  'tarot-trivia': {
    id: 'tarot-trivia',
    title: 'Master Trivia',
    description: 'The ultimate test of tarot lore and tradition.',
    component: lazy(() => import('./TarotTrivia/TarotTriviaGame'))
  },
  'luna-custom': {
    id: 'luna-custom',
    title: 'Luna\'s Secret Challenge',
    description: 'A unique challenge generated by Luna herself.',
    component: lazy(() => import('./LunaCustomGame/LunaCustomGame'))
  }
};
